### ISSUE TITLE
Remove copy?

### ISSUE THREAD

**Issue by knservis** [knservis/Gal-DINO#1]
This copy here obstructs the default execution (as the directory by default will be called Gal-DINO):

https://github.com/knservis/Gal-DINO/blob/4ff11c52af8d5b71e1b0a593553525e9a6f0d9e2/main.py#L277

I am thinking the command line argument "output_dir" should have a default value (e.g. `./output`) and I would refactor the code around that to improve reproducibility. 

What do you think @Nikhel1?

**Comment by Nikhel1** [comment]
Sure, this was added to keep records of changes in the codes for each run.
